# Generated by Django 5.0.4 on 2024-04-30 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHouseholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppr_backend.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppr_backend.user')),
            ],
            options={
                'db_table': 'user_households',
            },
        ),
        migrations.AddConstraint(
            model_name='userhouseholds',
            constraint=models.UniqueConstraint(fields=('user', 'household'), name='unique_user_households'),
        ),
    ]
