# Generated by Django 5.0.4 on 2024-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0002_userhouseholds_userhouseholds_unique_user_households'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhouseholds',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
