# Generated by Django 5.0.4 on 2024-05-01 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0003_alter_userhouseholds_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'shopping_list',
            },
        ),
        migrations.CreateModel(
            name='HouseholdShoppingList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppr_backend.household')),
                ('shoppingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppr_backend.shoppinglist')),
            ],
            options={
                'db_table': 'household_shopping_list',
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('shoppingList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppr_backend.shoppinglist')),
            ],
            options={
                'db_table': 'shopping_list_item',
            },
        ),
    ]
