# Generated by Django 5.0.4 on 2024-05-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0004_shoppinglist_householdshoppinglist_shoppinglistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
