# Generated by Django 5.0.4 on 2024-05-06 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
