# Generated by Django 5.0.4 on 2024-05-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0008_alter_household_id_alter_householdshoppinglist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
