# Generated by Django 5.0.4 on 2024-05-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0011_alter_user_managers_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
    ]
