# Generated by Django 5.0.4 on 2024-05-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0012_remove_user_created_at_remove_user_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='refreshToken',
        ),
    ]
