# Generated by Django 5.0.4 on 2024-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppr_backend', '0013_remove_user_refreshtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='refreshToken',
            new_name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
